spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: 'jdbc:h2:mem:mock'
    username: 'sa'
    password: 'webcomm'
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: ERROR
    tw.com.webcomm: DEBUG